export const CHANGE_CURRENT_SONG = 'player/CHANGE_CURRENT_SONG';

export const CHANGE_CURRENT_SONG_INDEX = 'player/CHANGE_CURRENT_SONG_INDEX';
export const CHANGE_PLAY_LIST = 'player/CHANGE_PLAY_LIST';

export const CHANGE_PLAY_SEQUENCE = 'player/CHANGE_PLAY_SEQUENCE';

export const CHANGE_FIRST_LOAD = 'player/CHANGE_FIRST_LOAD';

export const CHANGE_LYRIC_LIST = 'player/CHANGE_LYRIC_LIST';
export const CHANGE_CURRENT_LYRIC_INDEX = 'player/CHANGE_CURRENT_LYRIC_INDEX';

export const CHANGE_ADD_SONG_DETAIL = 'player/CHANGE_ADD_SONG_DETAIL';
export const CHANGE_PLAY_LIST_COUNT = 'player/CHANGE_PLAY_LIST_COUNT';
export const CHANGE_CURRENT_TOTAL = 'player/CHANGE_CURRENT_TOTAL';

export const CHANGE_HOT_COMMENT = 'player/CHANGE_HOT_COMMENT';
export const CHANGE_NEW_COMMENT = 'player/CHANGE_NEW_COMMENT';
export const CHANGE_PAGE_TOTAL = 'player/CHANGE_PAGE_TOTAL';
export const CHANGE_CURRENT_PAGE = 'player/CHANGE_CURRENT_PAGE';

export const CHANGE_SONG_DETAIL_INFO = 'player/CHANGE_SONG_DETAIL_INFO';
export const CHANGE_DETAIL_LYRIC = 'player/CHANGE_DETAIL_LYRIC';

export const CHANGE_SIMILAR_SONG = 'player/CHANGE_SIMILAR_SONG';
export const CHANGE_SIMILAR_ALBUM = 'player/CHANGE_SIMILAR_ALBUM';
