export const CHANGE_LOGIN_USER_PLAYLIST = 'user/CHANGE_LOGIN_USER_PLAYLIST'
export const CHANGE_LOGIN_USER_LOVER_LIST = 'user/CHANGE_LOGIN_USER_LOVER_LIST'
export const CHANGE_REFRESH_LOGIN = 'user/CHANG_REFRESH_LOGIN'
export const CHANGE_LOGIN_STATUS = 'user/CHANGE_LOGIN_STATUS'

export const CHANGE_LOGIN_USER_INFO = 'user/CHANGE_LOGIN_USER_INFO'

export const CHANGE_USER_DETAIL = 'user/CHANGE_USER_DETAIL'