export const CHANGE_QR_KEY = 'login/CHANGE_QR_KEY'
export const CHANGE_QR = 'login/CHANGE_QR'
export const CHANGE_QR_CHECK = 'login/CHANGE_QR_CHECK'
export const CHANGE_REFRESH_LOGIN = 'login/CHANG_REFRESH_LOGIN'
export const CHANGE_LOGIN_STATUS = 'login/CHANGE_LOGIN_STATUS'
export const CHANGE_LOGOUT = 'login/CHANGE_LOGOUT'