export  const CHANGE_MV_DETAIL = 'mvPlayer/CHANGE_MV_DETAIL'
export const CHANGE_MV_URL = 'mvPlayer/CHANGE_MV_URL'
export const CHANGE_SIM_MV = 'mvPlayer/CHANGE_SIM_MV'
export const CHANGE_MV_COMMENTS = 'mvPlayer/CHANGE_MV_COMMENTS'
export const CHANGE_MV_DETAIL_INFO = 'mvPlayer/CHANGE_MV_DETAIL_INFO'