export const CHANGE_ALL_MV = 'mv/CHANGE_ALL_MV'
export const CHANGE_NEW_MV = 'mv/CHANGE_NEW_MV'
export const CHANGE_EXCLUSIVE_MV = 'mv/CHANGE_EXCLUSIVE_MV'
export const CHANGE_MV_RANKING = 'mv/CHANGE_MV_RANKING'