export const CHANGE_PLAYLIST_DETAIL = 'CHANGE_PLAYLIST_DETAIL'
export const CHANGE_PLAYLIST_ALL_SONGS = 'CHANGE_PLAYLIST_ALL_SONGS'
export const CHANGE_PLAYLIST_COMMENT = 'CHANGE_PLAYLIST_COMMENT'
export const CHANGE_PLAYLIST_SUBSCRIBER = 'CHANGE_PLAYLIST_SUBSCRIBER'