export const CHANGE_PLAYLIST_DETAIL = 'playlist/CHANGE_PLAYLIST_DETAIL'
export const CHANGE_PLAYLIST_ALL_SONGS = 'playlist/CHANGE_PLAYLIST_ALL_SONGS'
export const CHANGE_PLAYLIST_COMMENT = 'playlist/CHANGE_PLAYLIST_COMMENT'
export const CHANGE_PLAYLIST_SUBSCRIBER = 'playlist/CHANGE_PLAYLIST_SUBSCRIBER'